### ISSUE TITLE
Target class [Garbetjie\Http\RequestLogging\IncomingRequestLoggingMiddleware] does not exist. 

### ISSUE THREAD

**Issue by jus7uice** [garbetjie/http-request-logger#4]
Iam already adding the middleware to $middleware property.

```

use Garbetjie\Http\RequestLogging\IncomingRequestLoggingMiddleware;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \App\Http\Middleware\TrustProxies::class,
        \Fruitcake\Cors\HandleCors::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
	/* Logging */
	IncomingRequestLoggingMiddleware::class,
    ];

```

But, I got an error:

> Illuminate\Contracts\Container\BindingResolutionException
> Target class [Garbetjie\Http\RequestLogging\IncomingRequestLoggingMiddleware] does not exist. 

Please help me how to fix this. Thank you

**Comment by garbetjie** [comment]
Hi @jus7uice. I see the README is actually outdated - I have changes that I haven't committed in order to update the docs.

If you change your `use` line from `use Garbetjie\Http\RequestLogging\IncomingRequestLoggingMiddleware;` to `use Garbetjie\RequestLogging\Http\Middleware\IncomingRequestLoggingMiddleware;`, it should work.

I'll make some time soon to finish up the README updates, and push them up. Thanks for highlighting this.

**Comment by garbetjie** [comment]
Updated README has been published.
